
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'a b c S : X\n          | Yempty : X : Z T Z : a Z b\n          | empty T : c T\n          | empty Y : F W W : b W c\n          | empty F : a F\n          | empty'
    
_lr_action_items = {'a':([0,6,],[6,6,]),'c':([0,4,7,9,12,13,17,18,19,],[-3,9,-6,9,-3,-11,19,-5,-10,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,13,15,16,18,19,],[-3,0,-1,-2,-3,-3,-3,-6,-4,-3,-8,-9,-11,-12,-7,-5,-10,]),'b':([0,5,6,7,12,14,15,18,],[-3,12,-3,-6,12,18,-12,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'X':([0,],[2,]),'Y':([0,],[3,]),'Z':([0,6,],[4,14,]),'F':([0,6,],[5,15,]),'empty':([0,4,5,6,9,12,],[7,10,13,7,10,13,]),'T':([4,9,],[8,16,]),'W':([5,12,],[11,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> X','S',1,'p_S','P7-ex3.py',17),
  ('S -> Y','S',1,'p_S','P7-ex3.py',18),
  ('empty -> <empty>','empty',0,'p_empty','P7-ex3.py',23),
  ('X -> Z T','X',2,'p_X','P7-ex3.py',28),
  ('Z -> a Z b','Z',3,'p_Z','P7-ex3.py',33),
  ('Z -> empty','Z',1,'p_Z','P7-ex3.py',34),
  ('T -> c T','T',2,'p_T','P7-ex3.py',38),
  ('T -> empty','T',1,'p_T','P7-ex3.py',39),
  ('Y -> F W','Y',2,'p_Y','P7-ex3.py',43),
  ('W -> b W c','W',3,'p_W','P7-ex3.py',47),
  ('W -> empty','W',1,'p_W','P7-ex3.py',48),
  ('F -> a F','F',2,'p_F','P7-ex3.py',52),
  ('F -> empty','F',1,'p_F','P7-ex3.py',53),
]
